# Cacheing
cache:
  paths:
    - node_modules/
    - public_html/bower_components/
    # - vendor

before_script:
  # Install dependencies
  - npm install
  - bower install --allow-root
  # Uncomment out the following 4 lines for Composer-based projects
  # - touch composer.lock
  # - rm composer.lock
  # - composer install --prefer-source --no-interaction
  # - composer dumpautoload
  # Build steps
  - if [ "$CI_BUILD_REF_NAME" == "production" ] || [ "$CI_BUILD_REF_NAME" == "master" ] ; then gulp --prod --hint; else gulp --maps --hint; fi
  # Set permissions to something the web server can use
  # - ./perm.sh
  # Add private key so we can connect to destination server
  - echo "$SSH_PRIVATE_KEY" > id_rsa
  - chmod 0600 id_rsa

deploy_prod:
  script:
    - rsync --copy-unsafe-links -prvzcSle 'ssh -p 22 -o StrictHostKeyChecking=no -i id_rsa' --exclude-from=.rsyncignore --exclude=public_html/src ./ user@ip:/path/to/project/
  stage: deploy
  only:
    - production

deploy_stage:
  script:
    - rsync --copy-unsafe-links -prvzcSle 'ssh -p 22 -o StrictHostKeyChecking=no -i id_rsa' --exclude-from=.rsyncignore ./ user@ip:/path/to/project/
  stage: deploy
  only:
    - master

deploy_dev:
  script:
    - rsync --copy-unsafe-links -prvzcSle 'ssh -p 22 -o StrictHostKeyChecking=no -i id_rsa' --exclude-from=.rsyncignore ./ user@ip:/path/to/project/
  stage: deploy
  only:
    - develop
