before_script:
  # Cacheing
  - mkdir -p /cache/{node_modules,bower_components}
  - ln -s /cache/node_modules node_modules
  - ln -s /cache/bower_components public_html/bower_components
  # Install dependencies
  - npm install
  - bower install --allow-root
  # Build steps
  - if [ "$CI_BUILD_REF_NAME" == "production" ] || [ "$CI_BUILD_REF_NAME" == "master" ] ; then gulp --prod --hint; else gulp --maps --hint; fi
  # Set permissions to something the web server can use
  # - ./perm.sh
  # Remove files that don't need to be synced to the server
  #   Symlink removal
  - rm node_modules public_html/bower_components
  #   Directories
  - rm -rf .git/ .sass-cache/ gulp/
  #   Prod has no sourcemaps, but other envs do, so conditionally remove src
  - if [ "$CI_BUILD_REF_NAME" == "production" ] ; then rm -rf public_html/src; fi
  #   Dotfiles and config files relevant only for compilation and dev
  - rm .bowerrc .gitignore .jscsrc .jshintrc .npmrc .scss-lint.yml bower.json gulpfile.js package.json README.md
  # Add private key so we can connect to destination server
  - echo "$SSH_PRIVATE_KEY" > id_rsa
  - chmod 0600 id_rsa

deploy_prod:
  script:
    - rsync --copy-unsafe-links -prvzcSle 'ssh -p 22 -o StrictHostKeyChecking=no -i id_rsa' --exclude 'id_rsa' ./ user@ip:/path/to/project
  stage: deploy
  only:
    - production

deploy_stage:
  script:
    - rsync --copy-unsafe-links -prvzcSle 'ssh -p 22 -o StrictHostKeyChecking=no -i id_rsa' --exclude 'id_rsa' ./ user@ip:/path/to/project
  stage: deploy
  only:
    - master

deploy_dev:
  script:
    - rsync --copy-unsafe-links -prvzcSle 'ssh -p 22 -o StrictHostKeyChecking=no -i id_rsa' --exclude 'id_rsa' ./ user@ip:/path/to/project
  stage: deploy
  only:
    - develop
