linters:
  Comment:
    enabled: false
  Indentation: # Line should be indented 4 spaces, but was indented 2 spaces
    severity: warning
    width: 2
    character: space
  MergeableSelector:
    enabled: false
  SelectorFormat:
    enabled: false
  StringQuotes: # Prefer single quoted strings
    enabled: true
  SelectorDepth:
    max_depth: 3
  SelectorFormat:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  VendorPrefix:
    enabled: false
  ColorVariable:
    enabled: false
  NameFormat:
    placeholder_convention: ^.|%
  ColorKeyword:
    enabled: false
  PseudoElement:
    enabled: false
